-- CreateEnum
CREATE TYPE "Role" AS ENUM ('ADMIN', 'USER');

-- AlterTable
ALTER TABLE "User" ADD COLUMN     "password" TEXT NOT NULL DEFAULT 'TEMP_PASSWORD',
ADD COLUMN     "role" "Role" NOT NULL DEFAULT 'USER';
